//
//  SyntaxThemes.swift
//  Twig
//
//  Created by Luka Kerr on 26/4/18.
//  Copyright © 2018 Luka Kerr. All rights reserved.
//

import Foundation

// Array of available syntax highlighting themes
public let SYNTAX_THEMES: [String] = [
  "agate",
  "androidstudio",
  "arduino-light",
  "arta",
  "ascetic",
  "atelier-cave-dark",
  "atelier-cave-light",
  "atelier-dune-dark",
  "atelier-dune-light",
  "atelier-estuary-dark",
  "atelier-estuary-light",
  "atelier-forest-dark",
  "atelier-forest-light",
  "atelier-heath-dark",
  "atelier-heath-light",
  "atelier-lakeside-dark",
  "atelier-lakeside-light",
  "atelier-plateau-dark",
  "atelier-plateau-light",
  "atelier-savanna-dark",
  "atelier-savanna-light",
  "atelier-seaside-dark",
  "atelier-seaside-light",
  "atelier-sulphurpool-dark",
  "atelier-sulphurpool-light",
  "atom-one-dark",
  "atom-one-light",
  "brown-paper",
  "codepen-embed",
  "color-brewer",
  "darcula",
  "dark",
  "darkula",
  "default",
  "docco",
  "dracula",
  "far",
  "foundation",
  "github-gist",
  "github",
  "googlecode",
  "grayscale",
  "gruvbox-dark",
  "gruvbox-light",
  "hopscotch",
  "hybrid",
  "idea",
  "ir-black",
  "magula",
  "mono-blue",
  "monokai-sublime",
  "monokai",
  "obsidian",
  "ocean",
  "paraiso-dark",
  "paraiso-light",
  "pojoaque",
  "purebasic",
  "qtcreator-dark",
  "qtcreator-light",
  "railscasts",
  "rainbow",
  "routeros",
  "school-book",
  "solarized-dark",
  "solarized-light",
  "sunburst",
  "tomorrow-night-blue",
  "tomorrow-night-bright",
  "tomorrow-night-eighties",
  "tomorrow-night",
  "tomorrow",
  "vs",
  "vs2015",
  "xcode",
  "xt256",
  "zenburn"
]
